export const APPJSONFILES = {
    // RateList.js

    rateList: [
        { name: "Shalwar kameez aam", quantity: 1, price: 300 },
        { name: "Shalwar kameez cotton", quantity: 1, price: 400 },
        { name: "Shalwar kameez bosky", quantity: 1, price: 500 },
        { name: "Shalwar kameez karandi", quantity: 1, price: 600 },
        { name: "Shalwar kameez silk", quantity: 1, price: 800 },
        { name: "Shalwar kameez wool khaddar", quantity: 1, price: 700 },
        { name: "Shalwar kameez wool karma", quantity: 1, price: 750 },
        { name: "Ladies shalwar kameez aam", quantity: 1, price: 350 },
        { name: "Ladies shalwar kameez cotton", quantity: 1, price: 450 },
        { name: "Ladies shalwar kameez three piece", quantity: 1, price: 650 },
        { name: "Ladies shalwar kameez fancy", quantity: 1, price: 900 },
        { name: "Ladies shalwar kameez velvet", quantity: 1, price: 950 },
        { name: "Ladies shaawl", quantity: 1, price: 200 },
        { name: "Burqa", quantity: 1, price: 1200 },
        { name: "Sari", quantity: 1, price: 1500 },
        { name: "Lehenga", quantity: 1, price: 2000 },
        { name: "Dupatta aam", quantity: 1, price: 100 },
        { name: "Shameez", quantity: 1, price: 150 },
        { name: "Dupatta karhai wala", quantity: 1, price: 250 },
        { name: "Dress pant", quantity: 1, price: 500 },
        { name: "Pant jeans", quantity: 1, price: 600 },
        { name: "Shirt/T-shirt", quantity: 1, price: 200 },
        { name: "Pajama", quantity: 1, price: 150 },
        { name: "Banyan/underwear", quantity: 1, price: 50 },
        { name: "Roomal/moze", quantity: 1, price: 30 },
        { name: "Jersey", quantity: 1, price: 400 },
        { name: "Sweater", quantity: 1, price: 700 },
        { name: "Safari suit", quantity: 1, price: 1000 },
        { name: "Arabi kameez", quantity: 1, price: 500 },
        { name: "Dhoti", quantity: 1, price: 150 },
        { name: "Tie", quantity: 1, price: 100 },
        { name: "Pagri kalaf", quantity: 1, price: 200 },
        { name: "Pagri/pagha", quantity: 1, price: 120 },
        { name: "Garam chadar", quantity: 1, price: 800 },
        { name: "Bachgana piece", quantity: 1, price: 100 },
        { name: "Towel", quantity: 1, price: 200 },
        { name: "Bed sheet aam", quantity: 1, price: 300 },
        { name: "Bed sheet aam double", quantity: 1, price: 400 },
        { name: "Bed sheet fancy", quantity: 1, price: 600 },
        { name: "Bed sheet fancy double", quantity: 1, price: 700 },
        { name: "Bed cover aam", quantity: 1, price: 250 },
        { name: "Bed cover aam double", quantity: 1, price: 350 },
        { name: "Bed cover fancy", quantity: 1, price: 450 },
        { name: "Takya cover aam", quantity: 1, price: 50 },
        { name: "Takya cover fancy", quantity: 1, price: 100 },
        { name: "Coat single", quantity: 1, price: 1000 },
        { name: "Pant coat two piece", quantity: 1, price: 1500 },
        { name: "Pant coat three piece", quantity: 1, price: 2000 },
        { name: "Muffler", quantity: 1, price: 100 },
        { name: "Leather jacket", quantity: 1, price: 3000 },
        { name: "Overcoat", quantity: 1, price: 1800 },
        { name: "Long coat", quantity: 1, price: 2000 },
        { name: "Velvet coat", quantity: 1, price: 2200 },
        { name: "Waistcoat", quantity: 1, price: 500 },
        { name: "Jacket aam", quantity: 1, price: 1000 },
        { name: "Maxi", quantity: 1, price: 700 },
        { name: "Sherwani aam", quantity: 1, price: 1500 },
        { name: "Sherwani karhai wali", quantity: 1, price: 2500 },
        { name: "Kambal single", quantity: 1, price: 800 },
        { name: "Kambal double", quantity: 1, price: 1200 },
        { name: "Vicky razai single", quantity: 1, price: 1000 },
        { name: "Vicky razai double", quantity: 1, price: 1500 },
        { name: "Baby kambal", quantity: 1, price: 500 },
        { name: "Parday aam fi panel", quantity: 1, price: 300 },
        { name: "Parday jali wale fi panel", quantity: 1, price: 400 },
        { name: "Parday istri wale fi panel", quantity: 1, price: 500 },
        { name: "Carpet center piece", quantity: 1, price: 1000 },
        { name: "Carpet square feet", quantity: 1, price: 50 },
    ]
    
}